### ISSUE TITLE
Add challenge content to match lesson material

### ISSUE THREAD

**Issue by tomrule007** [garageScript/c0d3-app#1077]
# Description

Make sure each [sublesson](https://github.com/garageScript/c0d3-app/tree/master/content/lessons) has:
1) Challenge questions covering the material learned in the sublesson
2) A `mdx/ChallengeBar` at the bottom of the sublesson page telling the students which challenges they should attempt with a link to the challenges.

## Details

When moving the lesson material from notion.so to being self hosted mdx docs on c0d3.com the material got broken into parts identified as sublessons. To get higher student engagement it was thought that we should encourage students to start on the challenges before they finish reading all parts of the lesson, but it also pointed out some parts were not covered with the current challenge questions.

A `<ChallengeBar ...>` component was created and included at the bottom of each sublesson page for this encouragement (see the example screenshots from js0 sublessons below)

Example ChallengeBar from js0 sublessons
![js0part1](https://user-images.githubusercontent.com/17365077/131869176-3a271536-8cdd-4054-add7-76694b0f263c.png)
[js0/ sublesson part 1](https://www.c0d3.com/curriculum/js0/primitive_data_and_operators)
![js0part2](https://user-images.githubusercontent.com/17365077/131869188-bc562986-4688-439e-b02c-73113b855690.png)
[js0/ sublesson part2](https://www.c0d3.com/curriculum/js0/functions_and_execution_context)
\*Scroll to bottom of page to see challenge bar

During the initial migration of material from notion they had added todo ChallengeBar to each sublesson that was missing challenge questions (a copy of the todo messages is included below). This became a perceived roadblock from going live with the self hosted lessons, which did not make sense, because it was the exact same material we were using on notion with the only difference being we now have Titles for the sublesson parts instead of one giant lesson doc for each course.

So instead of waiting I just removed the todo challenge bars in pr #1079 and created this issue as a reminder that we would still like to update the challenge questions and add the challenge bars back to each sublesson that is missing them.

# TODO

These are links to all the sublessons that are still missing challenges / ChallangeBar and a copy of the the old challenge bar that had the todo message that was removed in pr #1079

- [ ] https://www.c0d3.com/js1/hypertext_markup_language
```
<ChallengeBar
  href="/curriculum/js1"
  description="Complete HTML challenges (TO-DO add HTML challenges)"
  title="Master your skill by solving challenges"
/>
```
- [ ] https://www.c0d3.com/js2/introduction_to_testing_inner_properties
```
<ChallengeBar
  href="/curriculum/js2"
  description="Complete HTML and testing challenges (TO-DO add these challenges)"
  title="Master your skill by solving challenges"
/>
```
- [ ] https://www.c0d3.com/js4/classes
```
<ChallengeBar
  href="/curriculum/js4"
  description="Complete class related challenges (add class related challenges)"
  title="Master your skill by solving challenges"
/>
```
- [ ] https://www.c0d3.com/js4/interactive_elements
```
<ChallengeBar
  href="/curriculum/js4"
  description="Add a few testing challenges?"
  title="Master your skill by solving challenges"
/>
```

**Comment by songz** [comment]
not sure I understand this, perhaps @tomrule007 you could further explain to @InerLeeLofgren and I

**Comment by songz** [comment]
got it thanks for the update!
