### ISSUE TITLE
next-auth integration - Subtasks

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1589]
**Before taking any of the subtasks, make sure to read the [design doc](https://github.com/garageScript/c0d3-app/issues/1550)**

- [ ] Update [authController](https://github.com/garageScript/c0d3-app/blob/master/graphql/resolvers/authController.ts) resolvers to not check for the `req.session` as it won't exist OR replace it with `getSession` if checking the session existence is necessary
- [ ] Update [signup resolver](https://github.com/garageScript/c0d3-app/blob/9ef7f28938c0b2353a615cb665147831efab5859/graphql/resolvers/authController.ts#L89) to take a password argument and update the user in the db with the password along with the other user credentials.
   - 💡It'll deprecate the `/confirm/<token>` page
- [ ] Create next-auth types file for `useSession` and `getSession`
- [ ] Update [nextauth](https://github.com/garageScript/c0d3-app/blob/master/pages/api/auth/[...nextauth].ts) middleware with the callbacks and providers need to achieve the following:
   - Handle Login/Singup
   - Handle connect-to-discord
   - Handle sign-in with discord
<details>
  <summary>Initial attempt</summary>

```ts
import { NextApiResponse } from 'next'
import NextAuth from 'next-auth'
import CredentialsProvider from 'next-auth/providers/credentials'
import DiscordProvider from 'next-auth/providers/discord'
import { login, signup } from '../../../helpers/controllers/authController'
import { Context, LoggedRequest } from '../../../@types/helpers'
import { PrismaClient } from '@prisma/client'
import { session } from '../../../graphql/queryResolvers/session'
import { getSession } from 'next-auth/react'
import { Session } from '../../../@types/auth'
import { URL } from 'url'
import { updateRefreshandAccessTokens } from '../../../helpers/discordAuth'

const prisma = new PrismaClient()

const populateUser = async (
  user: { id: number },
  req: LoggedRequest,
  context: Context
) => {
  const userData = await prisma.user.findUnique({
    where: { id: user.id }
  })

  req.user = userData
  const userSession = await session(undefined, undefined, context)

  return {
    ...userSession,
    user: {
      id: userSession.user!.id,
      username: userSession.user?.username,
      name: userSession.user!.name,
      isAdmin: userSession.user?.isAdmin,
      isConnectedToDiscord: userSession.user?.isConnectedToDiscord,
      createdAt: userSession.user?.createdAt
    }
  }
}

export default (req: LoggedRequest, res: NextApiResponse) =>
  NextAuth(req, res, {
    providers: [
      CredentialsProvider({
        name: 'Credentials',
        credentials: {
          username: {
            label: 'Username',
            type: 'text',
            placeholder: 'Username'
          },
          password: {
            label: 'Password',
            type: 'password',
            placeholder: 'Password'
          },
          email: {
            label: 'Email',
            type: 'text',
            placeholder: 'Email'
          },
          firstName: {
            label: 'FirstName',
            type: 'text',
            placeholder: 'First name'
          },
          lastName: {
            label: 'LastName',
            type: 'text',
            placeholder: 'Last name'
          }
        },
        async authorize(credentials) {
          try {
            const context = { req, res } as Context

            const email = credentials?.email
            const firstName = credentials?.firstName
            const lastName = credentials?.lastName
            const username = credentials?.username
            const password = credentials?.password

            const isSignupFlow = firstName && lastName && email && username && password
            const isLoginFlow = username && password

            if (isSignupFlow) {
              const user = await signup(
                undefined,
                { email, lastName, firstName, username, password },
                context
              )

              if (user) {
                return await populateUser(user, req, context)
              }
            }

            if (isLoginFlow) {
              const user = await login(
                undefined,
                { username, password },
                context
              )

              if (user) {
                return await populateUser(user, req, context)
              }
            }

            return null
          } catch (e) {
            console.log(e)
            throw new Error(e as string)
          }
        }
      }),
      DiscordProvider({
        clientId: process.env.DISCORD_CLIENT_ID,
        clientSecret: process.env.DISCORD_CLIENT_SECRET
      })
    ],
    callbacks: {
      async signIn({ account, user }) {
        const { provider } = account

        if (provider === 'discord') {
          const session = (await getSession({ req })) as Session
          const { access_token, expires_at, refresh_token } = account

          // Connect to discord
          if (session?.user) {
            await updateRefreshandAccessTokens(
              session.user.id,
              user.id,
              refresh_token!,
              access_token!,
              new Date(expires_at! * 1000)
            )

            // Cancel auth flow. Session won't be created
            return '/discord/success'
          }

          // Sign-in to discord
          const userInfo = await prisma.user.findFirst({
            where: {
              discordId: user.id
            }
          })

          if (userInfo) return true
          return '/discord/user404'
        }

        return true
      },
      async session({ session, token }) {
        const context = { req, res } as Context
        const callbackUrl = new URL(req.cookies['next-auth.callback-url'])
        let user = token.user as object

        // /curriculum means it's sign-in to discord request
        if (callbackUrl.pathname === '/curriculum') {
          const userData = await prisma.user.findFirst({
            where: {
              discordId: token.sub
            }
          })

          user = await populateUser({ id: userData?.id! }, req, context)
        }

        session = { ...session, ...user }
        return session
      },
      async jwt({ token, user }) {
        if (user) {
          token.user = user
        }
        return token
      }
    }
    // debug: true
  })

```
</details>

- [ ]  Wrap the app component with the [SessionProvider](https://next-auth.js.org/getting-started/client#sessionprovider)

<details>
  <summary>Example code</summary>

```ts
import { Submission } from '@prisma/client'
import { DefaultSession } from 'next-auth'
import { SessionContextValue } from 'next-auth/react'

export interface Session extends DefaultSession {
  lessonStatus: {
    starGiven: string
    passedAt: Date | null
    lessonId: number
  }[]
  user: {
    id: number
    username: string
    name: string
    isAdmin: boolean
    isConnectedToDiscord: boolean
  }
  submissions: Submission[]
}

export declare type SessionContext<R extends boolean = false> = R extends true
  ?
      | {
          data: Session
          status: 'authenticated'
        }
      | {
          data: null
          status: 'loading'
        }
  :
      | {
          data: Session
          status: 'authenticated'
        }
      | {
          data: null
          status: 'unauthenticated' | 'loading'
        }

```
</details>

- [ ] Populate the `req.user` with the session in `getSession({ req })` in [user middleware](https://github.com/garageScript/c0d3-app/blob/master/helpers/middleware/user.ts)
- [ ] Update [updateRefreshandAccessTokens](https://github.com/garageScript/c0d3-app/blob/9ef7f28938c0b2353a615cb665147831efab5859/helpers/discordAuth.ts#L38) function to take a `discordId` and update the user data with it
- [ ] Update connectToDiscordModal component [signup button](https://github.com/garageScript/c0d3-app/blob/9ef7f28938c0b2353a615cb665147831efab5859/components/ConnectToDiscordModal.tsx#L79) to call `signIn('discord', { callbackUrl: '/discord/success' })`
- [ ] Update `success` page [getServerSideProps](https://github.com/garageScript/c0d3-app/blob/9ef7f28938c0b2353a615cb665147831efab5859/pages/discord/success.tsx#L176) to get the ID from `getSession`, lookup the user from the database, pass the user to [getDiscordInfo](https://github.com/garageScript/c0d3-app/blob/9ef7f28938c0b2353a615cb665147831efab5859/helpers/discordAuth.ts#L117) and return it as props
- [ ] Update [logoutContainer](https://github.com/garageScript/c0d3-app/blob/master/components/LogoutContainer.tsx) to call [signOut](https://next-auth.js.org/getting-started/client#signout) for signing out (log out)
- [ ] Update [lesson page](https://github.com/garageScript/c0d3-app/blob/b56cb061d4f7efe0e515ac7ba16816a0985798b7/pages/review/%5Blesson%5D.tsx) to get the session from `useSession`
- [ ] Update [lessonSlug](https://github.com/garageScript/c0d3-app/blob/b56cb061d4f7efe0e515ac7ba16816a0985798b7/pages/curriculum/%5BlessonSlug%5D.tsx) to get the session from `useSession`
- [ ] Update [curriculum page](https://github.com/garageScript/c0d3-app/blob/b56cb061d4f7efe0e515ac7ba16816a0985798b7/pages/curriculum.tsx) to get the session from `useSession` 
- [ ] Replace [login page](https://github.com/garageScript/c0d3-app/blob/b56cb061d4f7efe0e515ac7ba16816a0985798b7/pages/login.tsx) handleSubmit with `signIn('credentials', { redirect: false, ...values }`
- [ ] Replace [signup page](https://github.com/garageScript/c0d3-app/blob/b56cb061d4f7efe0e515ac7ba16816a0985798b7/pages/signup.tsx) handleSubmit with `signIn('credentials', { redirect: false, ...values }`

**Comment by flacial** [comment]
The file is unnecessary because the needed tasks are broken into 3:

- Connect to discord
- Signin with discord
- Login/Signup with next-auth credentials provider
